### ISSUE TITLE
Is it possible to parallelize `lmbtr.create` when working on one `ase.Atoms` object?

### ISSUE THREAD

**Issue by ARostekMU** [SINGROUP/dscribe#105]
Hi,

I am creating descriptors like this
```
lmbtr.create(atoms, n_jobs=-1)
```
where `atoms` is a `ase.Atoms` object and `lmbtr` is `dscribe.descriptors.lmbtr` object. The results are fine, but the computation always runs only on one core. 

It this expected behavior? Is parallelization possible only for multiple `ase.Atoms` objects?

**Comment by lauri-codes** [comment]
Hi @ARostekMU,

The parallellization is only effective when working on multiple systems. We do not parallelize the computations for a single system, as this is much trickier to implement. Our documentation should be updated to point out this fact better.

**Comment by ARostekMU** [comment]
Thank you for your answer.

If I were to split my `ase.Atoms` into multiple `ase.Atoms` and pass them to `create` in a `list`, would that give incorrect results?

**Comment by lauri-codes** [comment]
Depends how you do the splitting. The systems that you feed in still need to contain all of the neighbouring atoms within the cutoff radius from the LMBTR centers.

Such splitting might help if you have problems with memory, but I don't think it will make the computation faster as compared to feeding the system as a whole.
