### ISSUE TITLE
Descriptor that recognizes each atom of the same species differently

### ISSUE THREAD

**Issue by siddarthachar** [SINGROUP/dscribe#110]
Hi,

This is probably not an "issue".

I want to know if there's a descriptor available in the current version of Dscribe that can recognize each atom (of the same species) differently. For example, a symmetric relaxed ethene molecule has two C atoms and 4 H atoms, I would want to generate fingerprints the recognizes each C atom differently (though they are symmetric). I am using these descriptors to train a model that uses spatial data having different values at different atomic centers. I have been using SOAP for data that is symmetric w.r.t. geometries, and it seems to work perfectly. However, the same can not work for data that is not symmetric, which is obvious. 

Do you know of modifications or post-processing that can be done to enable this feature that I mentioned? Please let me know if this makes sense. 

Thanks!

**Comment by lauri-codes** [comment]
Hi @siddarthachar,

You can achieve something like this by changing the species of the carbon atoms in the underlying `ase.Atoms` object. Unfortunately `ase.Atoms` does not support using non-chemical symbols, so you would need to name these carbon atoms according to some actual element: one carbon could remain as "C", whereas the other carbon could be encoded as uranium "U". This approach is not very elegant, but gets the job done. We could think about using e.g. some special info into the `ase.Atoms` to determine the species in the future.
