### ISSUE TITLE
ACSF.create cannot accept cartesian positions as "centers" parameter

### ISSUE THREAD

**Issue by lophocinalis** [SINGROUP/dscribe#121]
The comment/guide writes that the centers parameter of the create function in the ACSF class can be cartesian positions, while it actually only accepts atomic indices.

**Comment by lauri-codes** [comment]
Thanks for the report! I will change this in the upcoming release for v2.1.0.

**Comment by lauri-codes** [comment]
Fixed in v2.1.0.
