### ISSUE TITLE
Similarity value is different between equivalent atoms

### ISSUE THREAD

**Issue by Firaskigali** [SINGROUP/dscribe#129]
Dear all,
This might be an "issue".

I want to know why the SOAP descriptor available in the current version of Dscribe represents an atom and its corresponding equivalent atoms in a supercell differently; this leads to different similarity values between those atoms.

For example, I made a 2x2x2 supercell, where I have a certain number of equivalent atoms. I computed their similarity based on the SOAP descriptor and by using the average kernel. If the cell is cubic, I get the correct numbers (similarity is very close to 1). If the cell is not cubic, I get different numbers (similarity is not close to 1). Why is that?

Do you know an explanation of this or any modifications or post-processing that can be done?
Firas

**Comment by lauri-codes** [comment]
Hi @Firaskigali,

Thank you for your question. I would need a minimal non-working example to reproduce this behaviour. I can't seem to reproduce the issue with a minimal example like this:

```python
from dscribe.descriptors import SOAP
from ase.build import bulk

soap_descriptor = SOAP(species=['Cu'], n_max=2, l_max=2, r_cut=5, periodic=True)

system_1x1 = bulk("Cu", "fcc")
features_1x1 = soap_descriptor.create(system_1x1, centers=[0])

system_3x3 = bulk("Cu", "fcc") * [3, 3, 3]
features_3x3 = soap_descriptor.create(system_3x3, centers=[0])

diff = features_1x1-features_3x3
print(diff.max())
```
where difference seems to be well below numerical accuracy of floating point operations.

Are you sure that you have set periodic boundary conditions correctly both in the descriptor, and in your `ASE.Atoms`?

**Comment by Firaskigali** [comment]
[data.zip](https://github.com/SINGROUP/dscribe/files/13380762/data.zip)
Hi lauri, 
Thank you for your response and your example.  I have attached two data files: one contained a unit cell of a monoclinic ZrO2 system, and the second file is a 2x2x2 of the unit cell. Then the issue comes when I try to compute the similarity between the first atom, "Zr," in the unit cell and its equivalent atoms in the supercell (the first 8 atoms) as follows:

`unit_cell_mono, super_cell_mono          =  'ZrO2_mono_111.xyz', 'ZrO2_mono_222.xyz'
system_1x1     = ase.io.read(unit_cell_mono,':')
system_2x2     = ase.io.read(super_cell_mono,':')

metric_soap    = AverageKernel(metric="polynomial",gamma=None, degree=4, coef0=1.0, normalize_kernel=True)
soap_descriptor = SOAP(species=['Zr','O'], rcut=2.5, nmax=10, lmax=10, sigma=0.5, periodic=True, rbf='polynomial',crossover=True, sparse=False)

features_1x1 = soap_descriptor.create(system_1x1)
features_2x2 = soap_descriptor.create(system_2x2)

diff = features_1x1[0] - features_2x2 [0] 
#diff is not equal to zero

CUB_MONO = []
for j in range(0,8):
    sim_kernel = metric_soap.create([features_1x1[0].reshape(1, -1), features_2x2[j].reshape(1, -1)])
    CUB_MONO.append(sim_kernel[0][1])
    print(j, sim_kernel[0][1])
print(np.mean(CUB_MONO))`

The output shows that the average similarity between equivalent atoms is not very close to one, as we can see in your example.  Why is that? Do you know an explanation of this or any modifications or post-processing that can be done?

Thank you in advance,
Firas

**Comment by Firaskigali** [comment]
> unit_cell_mono, super_cell_mono = 'ZrO2_mono_111.xyz', 'ZrO2_mono_222.xyz'
system_1x1 = ase.io.read(unit_cell_mono,':')
system_2x2 = ase.io.read(super_cell_mono,':')

metric_soap = AverageKernel(metric="polynomial",gamma=None, degree=4, coef0=1.0, normalize_kernel=True)
soap_descriptor = SOAP(species=['Zr','O'], rcut=2.5, nmax=10, lmax=10, sigma=0.5, periodic=True, rbf='polynomial',crossover=True, sparse=False)

features_1x1 = soap_descriptor.create(system_1x1)
features_2x2 = soap_descriptor.create(system_2x2)

diff = features_1x1[0] - features_2x2 [0]
#diff is not equal to zero

CUB_MONO = []
for j in range(0,8):
sim_kernel = metric_soap.create([features_1x1[0].reshape(1, -1), features_2x2[j].reshape(1, -1)])
CUB_MONO.append(sim_kernel[0][1])
print(j, sim_kernel[0][1])
print(np.mean(CUB_MONO))

**Comment by lauri-codes** [comment]
Hi @Firaskigali,

There is a problem in your structure file `ZrO2_mono_222.xyz`: it is not a 2x2x2 version of the unit cell, but instead contains some sort of a rotation of the atom positions.

If you e.g. use ASE to create the 2x2x2 system, you should get correct behaviour:
`system_2x2  = system_1x1 * [2, 2, 2]`

Below is a full example (base on dscribe==2.1.0, hence the syntax differences) of your script, from which I get the maximum absolute difference of 3.5373242421136986e-13 between the descriptor values.

```python
import numpy as np
import ase.io
from dscribe.descriptors import SOAP
from dscribe.kernels import AverageKernel

unit_cell_mono = 'ZrO2_mono_111.xyz'
system_1x1 = ase.io.read(unit_cell_mono, 0)
system_2x2 = system_1x1 * [2, 2, 2]

metric_soap = AverageKernel(
    metric="polynomial",
    gamma=None,
    degree=4,
    coef0=1.0,
    normalize_kernel=True
)
soap_descriptor = SOAP(
    species=['Zr','O'],
    r_cut=2.5,
    n_max=10,
    l_max=10,
    sigma=0.5,
    periodic=True,
    rbf='polynomial',
    compression={"mode": "crossover"},
    sparse=False
)

features_1x1 = soap_descriptor.create(system_1x1)
features_2x2 = soap_descriptor.create(system_2x2)

max_diff = np.max(np.abs(features_1x1[0] - features_2x2[0]))
print(f"Maximum difference in SOAP desciptor: {max_diff}")

CUB_MONO = []
for j in range(0, 8):
    sim_kernel = metric_soap.create([features_1x1[0].reshape(1, -1), features_2x2[j].reshape(1, -1)])
    CUB_MONO.append(sim_kernel[0][1])
    print(j, sim_kernel[0][1])
print(np.mean(CUB_MONO))
```

**Comment by lauri-codes** [comment]
Closing as inactive.

**Comment by Firaskigali** [comment]
Thank you very much for your help. I duplicated the unit cell as you suggested, and everything is fine now. Thank you.
