### ISSUE TITLE
Periodicity for ACSF

### ISSUE THREAD

**Issue by lauri-codes** [SINGROUP/dscribe#13]
Currently, ACSF does not support periodic systems. It could, however, be easily extended to support periodicity by using the cutoff radius to determine the periodic neighbours.

**Comment by lauri-codes** [comment]
Now implemented and tested in git master branch.

**Comment by sirmarcel** [comment]
Can you already predict in which release version this will be enabled?

**Comment by lauri-codes** [comment]
This will be included in the next release (0.3.0), but I will include a couple of other improvements before I make that release. If you need the periodicity urgently just clone the master branch and install it.

**Comment by sirmarcel** [comment]
Okay, thanks. No worries, just wanted to make sure I get the version requirement right for `cscribe`.
