### ISSUE TITLE
Analytic Integral of SH expansion coefficients

### ISSUE THREAD

**Issue by hypefolder** [SINGROUP/dscribe#132]
In your paper you mention that using a GTO radial basis function ($g_n$) in the atomic density expansion

$$
\rho(r)= \sum\limits_{nlm}g_n(r)Y_{lm}(\theta, \phi)
$$

the coefficients can be obtained through the following integral

$$
c_{n l m}^Z=\iiint_{R^3} dV g_n(r) Y_{l m}(\theta, \phi) \rho^Z(\boldsymbol{r}) .
$$

can be computed analytically. Is there any source, from your paper or otherwise where the formula for analytic integration is explicitly shown? If not, where in the code can I see how this integral is computed directly (i.e. not numerically).

Thank you for your help in advance!

**Comment by lauri-codes** [comment]
Hi @hypefolder!

We do indeed have this in the Supplementary Information of our [latest paper](https://doi.org/10.1063/5.0151031), here is a direct [link to the zip file containing the PDF](https://pubs.aip.org/jcp/article-supplement/2897350/zip/234802_1_5.0151031.suppl_material/). The important part is in S3 (Smooth Overlap of Atomic Positions (SOAP) with Gaussian type orbital (GTO) radial basis).

In this document I tried to explain the process as best as I could, but at least for me, it is still very complicated... But I do hope that this document gets you started.

-Lauri

**Comment by hypefolder** [comment]
Hello Lauri,

Thank you very much for the link; I completely missed your latest paper. 

The supplementary information is very clear, I have not seen anybody else go into this much detail and it is much appreciated :smile:.

Best,

hypefolder
