### ISSUE TITLE
ACSF G5 values

### ISSUE THREAD

**Issue by hmhoseini** [SINGROUP/dscribe#138]
Hello,
I am calculating ACSF for a structure with 48 B atoms. The structure is available at Materials Project database "mp-570316". 
While the values for  G2 and G4 are correct, the values for G5 for the following parameters are printed as inf and -inf.

symmetry = {'G5': {'Rs': [0], 'lambda': [1, -1], 'zeta': [1,2,4,12], 'eta': [0.2270, 0.0504, 0.0144, 0.0011]}}

The structure (cif) and the expected G5 values are attached.  

Best regards,
Hossein Mirhosseini
[B.zip](https://github.com/SINGROUP/dscribe/files/14741728/B.zip)

**Comment by lauri-codes** [comment]
Hi @hmhoseini!

Thanks for pointing this out. This is a bug in the ACSF G5 calculation. I will include a fix for this in the next version.

**Comment by lauri-codes** [comment]
This problem is now fixed in v2.1.1.
