### ISSUE TITLE
Derivative of SOAP 

### ISSUE THREAD

**Issue by lmj1029123** [SINGROUP/dscribe#14]
Hi,

Is there a way to get the derivative of the SOAP descriptor corresponding to the positions? I believe the derivative is necessary if I want to do force training. I couldn't find documentation about it. Thanks!

**Comment by Aki78** [comment]
Hi,
Analytical derivatives of SOAP for the GTO basis are possible, but there will be a lot of grinding calculations (see the last few pages in https://github.com/SINGROUP/SOAPLite/blob/master/soapDoc.pdf 
) . Numerical derivatives are also possible and a bit easier to implement, but the computations will be heavy and would be quite slow. At the moment we don't have plans to implement either.

**Comment by lmj1029123** [comment]
Thanks!
