### ISSUE TITLE
SOAP_sparse=True

### ISSUE THREAD

**Issue by mansoure37** [SINGROUP/dscribe#141]
Hi Lauri
when I put  sparse=True, I get thise error  "Cannot convert a sparse array to dense automatically. To manually densify, use the todense method." what should I do?

soap=SOAP(
    species=species,
    r_cut=2,
    n_max=3,
    l_max=2,
    average="inner",
    periodic=True,
    sparse=True,  
    dtype='float64')

thank you

**Comment by lauri-codes** [comment]
Hi @mansoure37!

There is probably some piece of code missing in your example. Could you post a full script that I could run to reproduce the error? If I try to run something like this:



```python
from ase.build import molecule
from dscribe.descriptors import SOAP

water = molecule("H2O")
soap = SOAP(
    species=["H", "O"],
    r_cut=6.0,
    n_max=8,
    l_max=6,
    sparse=True
)
soap_water = soap.create(water)
print(type(soap_water))  # <class 'sparse._coo.core.COO'>
```

I don't see any errors. Maybe you are doing some calculation with the output vector or feeding it into a ML model that does not support sparse algebra...?

**Comment by lauri-codes** [comment]
Closing as stale.
