### ISSUE TITLE
Molecular representations for bio-molecules

### ISSUE THREAD

**Issue by CalmScout** [SINGROUP/dscribe#144]
Dear maintainers of DScribe package,

Thank you for the nice package that provides easy access to the alternative to classical (Morgan fingerprints, MACCS, etc.) molecular representations. May I ask you which of the representations besides Coulomb Matrix from your package are applicable to biochemistry tasks (non-crystalls)?

Best regards,
Anton.

**Comment by lauri-codes** [comment]
Hi @CalmScout,

I would say this depends a bit on what kind of description you are looking for: are you interested in describing a feature that is localized (e.g. binding site in a protein) or a feature that depends on the global structure of a molecule (e.g. formation energy)?

For local features, I would recommend [SOAP](https://singroup.github.io/dscribe/latest/tutorials/descriptors/soap.html), for global features I would recommend [MBTR](https://singroup.github.io/dscribe/latest/tutorials/descriptors/mbtr.html). With these two you can get started.

-Lauri
