### ISSUE TITLE
MBTR k2, k3

### ISSUE THREAD

**Issue by sandipgiri576** [SINGROUP/dscribe#147]
I am geeting some issue when trying some example with k1, k2 and k3 together. Looks like the the new mbtr file got changed, ````
import numpy as np
from ase import Atoms
from dscribe.descriptors import MBTR
from ase.build import molecule

def Atom_XYZ(new_struct):
    if new_struct == "water":
        atoms = ['O', 'H', 'H']
        charges = [8, 1, 1]
        coords = [
            [0.0000,  0.0000,  0.0000],
            [0.0000,  0.7570,  0.5860],
            [0.0000, -0.7570,  0.5860]
        ]
        return atoms, charges, coords
    else:
        raise ValueError("Structure not recognized")

def MBTR_test(new_struct):
    atoms, charges, coords = Atom_XYZ(new_struct)
    species = np.unique(np.asarray(charges)).tolist()

    # Setup MBTR for k1, k2, and k3 separately
    mbtr = MBTR(
        species=species,
        geometry={"k2": {"function": "inverse_distance"}, "k3": {"function": "cosine"}},
        grid={
            "k2": {"min": 0, "max": 1, "n": 100, "sigma": 0.1},
            "k3": {"min": -1, "max": 1, "n": 100, "sigma": 0.1},
        },
        weighting={
            "k2": {"function": "exp", "scale": 0.5, "threshold": 1e-3},
            "k3": {"function": "exp", "scale": 0.5, "threshold": 1e-3},
        },
        normalize_gaussians=True,
        normalization="l2",
        periodic=False,
        sparse=False,
        dtype="float64"
    )

    mol = mbtr.create(Atoms(positions=coords, numbers=charges), n_jobs=1)
    return mol

# Test the MBTR function with the water molecule
water_mbtr = MBTR_test("water")
print(water_mbtr)

````  plaese have a look, and guide me to write the proper way of k1, k2 and k3 together.

**Comment by tangerdream** [comment]
I also found that this part of the code has indeed changed ([https://singroup.github.io/dscribe/latest/tutorials/descriptors/lmbtr.html#examples](https://singroup.github.io/dscribe/latest/tutorials/descriptors/lmbtr.html#examples)), but this has caused issues. As shown in this issue, how are the parameters related to k1 and k2 reflected in the new version (v 2.1.x) of MBTR?
I hope the developers can provide a demonstration.

**Comment by lauri-codes** [comment]
Hi @sandipgiri576!

Indeed the MBTR interface was changed in dscribe v2.0. The new interface requires you to specify and create the different k-terms with separate objects, and then merge them later. Here is an example:

```python
import numpy as np
from dscribe.descriptors import MBTR
from ase.build import molecule

systems = [molecule("H2O"), molecule("NO2")]
species = set().union(*[x.get_atomic_numbers() for x in systems])

# Setup K2
mbtr_k2 = MBTR(
    species=species,
    geometry={"function": "inverse_distance"},
    grid={"min": 0, "max": 1, "n": 100, "sigma": 0.1},
    weighting={"function": "exp", "scale": 0.5, "threshold": 1e-3},
    periodic=False,
)

# Setup K3
mbtr_k3 = MBTR(
    species=species,
    geometry={"function": "cosine"},
    grid={"min": -1, "max": 1, "n": 100, "sigma": 0.1},
    weighting={"function": "exp", "scale": 0.5, "threshold": 1e-3},
    periodic=False,
)

# Create both feature vectors and join them
k2 = mbtr_k2.create(systems)
k3 = mbtr_k3.create(systems)
full = np.concatenate((k2, k3), axis=1)
print(full.shape)
```

**Comment by sandipgiri576** [comment]
Yes, I was doing similar things to merge them. Thank you.
