### ISSUE TITLE
pip install error in MacOS 10.14.1 python3.6

### ISSUE THREAD

**Issue by HadXu** [SINGROUP/dscribe#16]
`nstalling collected packages: dscribe
  Running setup.py install for dscribe ... error
    Complete output from command /Users/xx/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/fk/by0sbjf95jd7cj8qddj6y0_40000gn/T/pip-n5ti89v0-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/fk/by0sbjf95jd7cj8qddj6y0_40000gn/T/pip-1ow0r_et-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe
    copying dscribe/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/kernels
    copying dscribe/kernels/rematch.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/kernels
    copying dscribe/kernels/localsimilaritykernel.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/kernels
    copying dscribe/kernels/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/kernels
    copying dscribe/kernels/average.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/kernels
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/core
    copying dscribe/core/system.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/core
    copying dscribe/core/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/core
    copying dscribe/core/lattice.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/core
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/utils
    copying dscribe/utils/species.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/utils
    copying dscribe/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/utils
    copying dscribe/utils/stats.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/utils
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/descriptor.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/elementaldistribution.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/matrixdescriptor.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/soap.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/coulombmatrix.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/acsf.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/sinematrix.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/lmbtr.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    copying dscribe/descriptors/mbtr.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/descriptors
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/libmbtr
    copying dscribe/libmbtr/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libmbtr
    creating build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf
    copying dscribe/libacsf/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf
    running egg_info
    creating dscribe.egg-info
    writing dscribe.egg-info/PKG-INFO
    writing dependency_links to dscribe.egg-info/dependency_links.txt
    writing requirements to dscribe.egg-info/requires.txt
    writing top-level names to dscribe.egg-info/top_level.txt
    writing manifest file 'dscribe.egg-info/SOURCES.txt'
    reading manifest file 'dscribe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'LICENSE.txt'
    writing manifest file 'dscribe.egg-info/SOURCES.txt'
    copying dscribe/libmbtr/mbtr.cpp -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libmbtr
    copying dscribe/libmbtr/mbtr.h -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libmbtr
    copying dscribe/libmbtr/mbtrwrapper.cpp -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libmbtr
    copying dscribe/libacsf/acsf.cpp -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf
    copying dscribe/libacsf/acsf.h -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf
    copying dscribe/libacsf/acsfwrapper.cpp -> build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf
    running build_ext
    building 'dscribe.libacsf.acsfwrapper' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/dscribe
    creating build/temp.macosx-10.7-x86_64-3.6/dscribe/libacsf
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xx/anaconda3/envs/py36/include -arch x86_64 -I/Users/xx/anaconda3/envs/py36/include -arch x86_64 -Idscribe/libacsf -I/Users/xx/anaconda3/envs/py36/include/python3.6m -c dscribe/libacsf/acsfwrapper.cpp -o build/temp.macosx-10.7-x86_64-3.6/dscribe/libacsf/acsfwrapper.o -std=c++11 -stdlib=libc++
    g++ -bundle -undefined dynamic_lookup -L/Users/xx/anaconda3/envs/py36/lib -arch x86_64 -L/Users/xx/anaconda3/envs/py36/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/dscribe/libacsf/acsfwrapper.o -o build/lib.macosx-10.7-x86_64-3.6/dscribe/libacsf/acsfwrapper.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/Users/xx/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/fk/by0sbjf95jd7cj8qddj6y0_40000gn/T/pip-n5ti89v0-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/fk/by0sbjf95jd7cj8qddj6y0_40000gn/T/pip-1ow0r_et-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fk/by0sbjf95jd7cj8qddj6y0_40000gn/T/pip-n5ti89v0-build/`

**Comment by lauri-codes** [comment]
Hi @HadXu,

Thank you for reporting this issue. We have experienced this problem before, and in principle know what is causing it. The issue is a bit hard for me to reproduce since this problem is not present in the macOS computers that we have tested on. It seems that the issue arises only there is a certain mismatch between the Xcode version you are using now and what Xcode version was used to build your python version.

I have however now introduced a possible fix in the development branch of the DScribe library. Would it be possible for you to test this version out? You would need to clone the development branch from GitHub and then try installing that version. The command to do this would be:

```sh
git clone --branch development https://github.com/SINGROUP/dscribe.git
cd dscribe
pip install .
```

Please respond to this issue thread if you could test this solution on your machine. This would help us a lot, and if we see that the problem is solved we can introduce the changes to the master branch.

**Comment by koukyo1994** [comment]
I faced the same problem but successfully installed with the advice, thanks!

**Comment by HadXu** [comment]
OOOOOK,Thanks
