### ISSUE TITLE
linux install error?

### ISSUE THREAD

**Issue by HadXu** [SINGROUP/dscribe#17]
`gcc: error: unrecognized command line option '-fno-plt'`

**Comment by lauri-codes** [comment]
Hi!

You seem to have a python version that has been compiled with a newer version of GCC that what you are currently using. Can you try upgrading to a newer GCC version (>= GCC 6)? On Ubuntu, you can [follow this guide](http://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu)

If updating gcc is not possible, then you will need to modify the compilation flags manually. Reply here if you need help with that.

**Comment by lauri-codes** [comment]
Closing this issue for now.
