### ISSUE TITLE
Can I set nmax and lmax larger?

### ISSUE THREAD

**Issue by lchaoyi** [SINGROUP/dscribe#19]
I am using SOAP to describe the local atomic environment of amorphous materials. However, I notice that there is a limit for number of basis functions and lmax (nmax cannot exceed 12 and lmax cannot exceed 9). 

I was wondering if I could set a larger value for nmax and lmax. That could help me to describe the local environment better.

**Comment by lauri-codes** [comment]
Hi @lchaoyi,

When using the GTO-radial basis, there is a hard limit of lmax=9. This is simply because the analytical formulas have not been yet extended beyond that (very tedious work).

If you know that you need to have a more detailed sampling of the neighbourhood, I would suggest switching to the polynomial radial basis (in the SOAP constructor specify: rbf="polynomial"), which supports bigger lmax and nmax. This basis is a bit slower to calculate, but should be almost identical in terms of how well it can represent the local neighbourhood.

Hope this helps!

**Comment by lchaoyi** [comment]
Thank you for your reply. That helps me a lot. However, when I set rbf as polynomial and let nmax be 18, the program shows ValueError：
Could not calculate normalization factors for the polynomial basis in the domain of real numbers. Lowering the number of radial basis function is advised.
Then I tried a smaller value of nmax (12), the program could run properly. I was wondering could I use Dscribe to depict local atomic environment with even larger number of radial basis function? Are there any ways to overcome this limit? (For example, could Dscribe get SOAP descriptor correctly when I set nmax as 18 ?)
Thank you for your generously help on this issue.

**Comment by lauri-codes** [comment]
Hi @lchaoyi,

The problem that you are facing relates to the fact that if you try to fit too many radial basis functions to a small radius (small rcut), they are very hard to numerically orthonormalize. This is essentially the error you are getting. You have reached the maximum density at which the radial basis can be sampled with your current rcut. You can probably increase nmax by increasing rcut, but that does not make your radial sampling any denser, only makes the sampled area radially bigger.

Typically there is however little benefit in going to very large nmax and lmax values. This does, however, depend on the application you are interested in. I would suggest that you first ensure that your target property has not already saturated with respect to nmax and lmax. If you are still seeing big improvements beyond lmax>9 and nmax > 12, let us know so we might be able to see if the numerics can be made more stable. Hope this helps!

**Comment by lchaoyi** [comment]
Hi @lauri-codes 

Thank you for your information. I have a better understanding of SOAP descriptor. I would look into details of my projects and then find out the influence of number of radial basis. I would let you know if I really need large number of basis.

I really appreciate your generous help.
