### ISSUE TITLE
SOAP kernel vs descriptor

### ISSUE THREAD

**Issue by bartolsthoorn** [SINGROUP/dscribe#21]
This is not a technical question but more a question about the philosophy of SOAP.

The way I understand SOAP is that it actually provides the kernel itself directly. In that way, it is more elegant than for example the old Coulomb matrix approach, where you first produce 1D array descriptors and then later choose a kernel (e.g. rbf) and fit.

However, in practice SOAP is often implemented as an inner product of the "power spectra" of each neighborhood. The power spectra are essentially 1D descriptors again, but really they are only there as an intermediate step towards the final goal of calculating the SOAP kernel. However, if you take anything else than an inner product you are spoiling the definition of the original SOAP, that is: the overlap of gaussians placed at atomic position for two environments. If you do not use the inner product you have something else, not the overlap.

With this in mind, I am bit surprised that you seem to use SOAP as a descriptor and not as the kernel itself, as it was originally designed. Is this on purpose? Did you find that using the SOAP descriptors in another kernel lead to better results?

**Comment by lauri-codes** [comment]
Hi @bartolsthoorn!

Thank you for the great question! This is a topic that has not been so clear to me either, but I will try to illustrate my view on it here.

You are indeed right that only by taking the inner product of the power spectras you will arrive at the correct overlap of the atomic environments. This original definition of the "SOAP kernel" (=polynomial kernel) is also explicitly [mentioned in our SOAP tutorial](https://singroup.github.io/dscribe/tutorials/soap.html).

Nothing in practice, however, restricts using any other kernel or other machine learning method on the power spectra. I would even say that the spectrum on its own is a more useful and general concept, as it is a vector that directly describes the atomic environment (it is not just a useless intermediate step.)

We have some experience on using other kernels (see section II B in the Supplementary Information [of this publication](https://doi.org/10.1038/s41524-018-0096-5)) and have noticed that e.g. the Gaussian Kernel performs at least as well for our particular application. Also, I would argue that in some cases using methods that are not based on kernels (=do not reduce the similarity to a single number), are a better fit. E.g. decision trees or neural networks may pick up on more complicated trends in the spectrum. Also, the spectra on its own can be used in other machine learning tasks, such as clustering.

Hope this helps!

**Comment by sirmarcel** [comment]
Hi,

(hope I'm not disturbing y'all),

Just wanted to second @lauri-codes; in our benchmarking (a paper is forthcoming), SOAP also performs extremely well with the Gaussian kernel!

I think it's perfectly valid to view SOAP as a descriptor -- it is simply a vector with the "correct" invariances (rotation, translation, etc.) and can be directly derived as such. Computing the "overlap" integral is one particular (but not the only) way of arriving at the SOAP definition, and one way to interpret the notion of "comparing" environments. There's nothing intrinsically "more" correct about it.

I also agree that using the spectrum is more convenient, and in some ways more elegant, since it separates the task of feature generation from regression, as it's usually done in ML.

Cheers!

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

Good to hear that you have had similar experiences!

I think the choice of using a polynomial kernel of the form `<p, p'>^\zeta` (eq. 36 in [1]) when measuring the similarity of two environments and dubbing this the "SOAP kernel" was a bit misleading. As far as I understand, this particular kernel is not required for some special reason but is a decision made by the authors. They certainly demonstrate that the dot product corresponds to the angular integral, so it should be a good idea to base the kernel on top of it, but the polynomial kernel is not the only choice. It is partly up to the user to benchmark different kernels functions, as there might be some differences depending on the application. The Gaussian kernel (which in fact can be shown to correspond to an infinite sum of polynomials of the form `<p, p'>^n`) should definitely be a valid choice as well.

[1] Albert P. Bartok, Risi Kondor, and Gabor Csanyi, On representing chemical environments, Phys. Rev. B (2013) 87, 184115

**Comment by bartolsthoorn** [comment]
Thank you all for the insightful comments, very useful! :+1:
