### ISSUE TITLE
error installing dscribe in WSL ubuntu in Win10 

### ISSUE THREAD

**Issue by jungsdao** [SINGROUP/dscribe#23]
I've used dscribe without any problem. When I erased WSL in my labtop ans reinstalled it, I got problem in the install. Following is my error message. 
I've check that I have proper version of wheel and can't think of any specific reason why It gives this problem. Any help would be appreciated. 
Thanks in advance

--Following is my error message --

Collecting dscribe
  Using cached https://files.pythonhosted.org/packages/fe/a5/fe085985e00b93d4a647fe24519bbaba3efe9d7c2e7efd6ef72107e8040f/dscribe-0.2.8.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from dscribe) (1.16.4)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from dscribe) (1.3.0)
Requirement already satisfied: ase in ./.local/lib/python3.7/site-packages (from dscribe) (3.18.0)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from dscribe) (0.17.1)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.7/site-packages (from dscribe) (0.21.2)
Requirement already satisfied: joblib in ./anaconda3/lib/python3.7/site-packages (from dscribe) (0.13.2)
Collecting soaplite==1.0.3 (from dscribe)
  Using cached https://files.pythonhosted.org/packages/4a/d2/164ae157724e182ba0b7549f0acfdfbcc87cb707009c52b56353d52750c2/soaplite-1.0.3.tar.gz
Requirement already satisfied: flask in ./anaconda3/lib/python3.7/site-packages (from ase->dscribe) (1.1.1)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.7/site-packages (from ase->dscribe) (3.1.0)
Requirement already satisfied: itsdangerous>=0.24 in ./anaconda3/lib/python3.7/site-packages (from flask->ase->dscribe) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./anaconda3/lib/python3.7/site-packages (from flask->ase->dscribe) (2.10.1)
Requirement already satisfied: click>=5.1 in ./anaconda3/lib/python3.7/site-packages (from flask->ase->dscribe) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in ./anaconda3/lib/python3.7/site-packages (from flask->ase->dscribe) (0.15.4)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->ase->dscribe) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->ase->dscribe) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->ase->dscribe) (2.4.0)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->ase->dscribe) (2.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->ase->dscribe) (1.1.1)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->ase->dscribe) (1.12.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->ase->dscribe) (41.1.0)
Building wheels for collected packages: dscribe, soaplite
  Building wheel for dscribe (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jungsdao/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vu613yhf/dscribe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vu613yhf/dscribe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e_96ptgc --python-tag cp37
       cwd: /tmp/pip-install-vu613yhf/dscribe/
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/dscribe
  copying dscribe/__init__.py -> build/lib.linux-x86_64-3.7/dscribe
  creating build/lib.linux-x86_64-3.7/dscribe/core
  copying dscribe/core/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/core
  copying dscribe/core/lattice.py -> build/lib.linux-x86_64-3.7/dscribe/core
  copying dscribe/core/system.py -> build/lib.linux-x86_64-3.7/dscribe/core
  creating build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/acsf.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/coulombmatrix.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/descriptor.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/elementaldistribution.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/lmbtr.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/matrixdescriptor.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/mbtr.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/sinematrix.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  copying dscribe/descriptors/soap.py -> build/lib.linux-x86_64-3.7/dscribe/descriptors
  creating build/lib.linux-x86_64-3.7/dscribe/kernels
  copying dscribe/kernels/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/kernels
  copying dscribe/kernels/average.py -> build/lib.linux-x86_64-3.7/dscribe/kernels
  copying dscribe/kernels/localsimilaritykernel.py -> build/lib.linux-x86_64-3.7/dscribe/kernels
  copying dscribe/kernels/rematch.py -> build/lib.linux-x86_64-3.7/dscribe/kernels
  creating build/lib.linux-x86_64-3.7/dscribe/libacsf
  copying dscribe/libacsf/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/libacsf
  creating build/lib.linux-x86_64-3.7/dscribe/libmbtr
  copying dscribe/libmbtr/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/libmbtr
  creating build/lib.linux-x86_64-3.7/dscribe/utils
  copying dscribe/utils/__init__.py -> build/lib.linux-x86_64-3.7/dscribe/utils
  copying dscribe/utils/geometry.py -> build/lib.linux-x86_64-3.7/dscribe/utils
  copying dscribe/utils/species.py -> build/lib.linux-x86_64-3.7/dscribe/utils
  copying dscribe/utils/stats.py -> build/lib.linux-x86_64-3.7/dscribe/utils
  running egg_info
  writing dscribe.egg-info/PKG-INFO
  writing dependency_links to dscribe.egg-info/dependency_links.txt
  writing requirements to dscribe.egg-info/requires.txt
  writing top-level names to dscribe.egg-info/top_level.txt
  reading manifest file 'dscribe.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'LICENSE.txt'
  writing manifest file 'dscribe.egg-info/SOURCES.txt'
  copying dscribe/libacsf/acsf.cpp -> build/lib.linux-x86_64-3.7/dscribe/libacsf
  copying dscribe/libacsf/acsf.h -> build/lib.linux-x86_64-3.7/dscribe/libacsf
  copying dscribe/libacsf/acsfwrapper.cpp -> build/lib.linux-x86_64-3.7/dscribe/libacsf
  copying dscribe/libmbtr/mbtr.cpp -> build/lib.linux-x86_64-3.7/dscribe/libmbtr
  copying dscribe/libmbtr/mbtr.h -> build/lib.linux-x86_64-3.7/dscribe/libmbtr
  copying dscribe/libmbtr/mbtrwrapper.cpp -> build/lib.linux-x86_64-3.7/dscribe/libmbtr
  running build_ext
  building 'dscribe.libacsf.acsfwrapper' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/dscribe
  creating build/temp.linux-x86_64-3.7/dscribe/libacsf
  gcc -pthread -B /home/jungsdao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Idscribe/libacsf -I/home/jungsdao/anaconda3/include/python3.7m -c dscribe/libacsf/acsfwrapper.cpp -o build/temp.linux-x86_64-3.7/dscribe/libacsf/acsfwrapper.o -std=c++11
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dscribe
  Running setup.py clean for dscribe
  Building wheel for soaplite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jungsdao/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n11l4nny --python-tag cp37
       cwd: /tmp/pip-install-vu613yhf/soaplite/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/soaplite
  copying soaplite/__init__.py -> build/lib.linux-x86_64-3.7/soaplite
  copying soaplite/core.py -> build/lib.linux-x86_64-3.7/soaplite
  copying soaplite/genBasis.py -> build/lib.linux-x86_64-3.7/soaplite
  copying soaplite/getBasis.py -> build/lib.linux-x86_64-3.7/soaplite
  running build_ext
  building 'lib.libsoapPySig' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -B /home/jungsdao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/jungsdao/anaconda3/include/python3.7m -c src/soapAnalFullPySigma.c -o build/temp.linux-x86_64-3.7/src/soapAnalFullPySigma.o -O3 -std=c99
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for soaplite
  Running setup.py clean for soaplite
Failed to build dscribe soaplite
Installing collected packages: soaplite, dscribe
  Running setup.py install for soaplite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/jungsdao/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xobg36k8/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-vu613yhf/soaplite/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/soaplite
    copying soaplite/__init__.py -> build/lib.linux-x86_64-3.7/soaplite
    copying soaplite/core.py -> build/lib.linux-x86_64-3.7/soaplite
    copying soaplite/genBasis.py -> build/lib.linux-x86_64-3.7/soaplite
    copying soaplite/getBasis.py -> build/lib.linux-x86_64-3.7/soaplite
    running build_ext
    building 'lib.libsoapPySig' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -B /home/jungsdao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/jungsdao/anaconda3/include/python3.7m -c src/soapAnalFullPySigma.c -o build/temp.linux-x86_64-3.7/src/soapAnalFullPySigma.o -O3 -std=c99
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/jungsdao/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vu613yhf/soaplite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xobg36k8/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by lauri-codes** [comment]
Hi @jungsdao,

The error message seems to suggest that your WSL installation is missing the GNU Compiler Collection (gcc): `unable to execute 'gcc': No such file or directory`

I have no experience with WSL, but I would think that gcc can be installed through the terminal with a command like this: `sudo apt install gcc g++`

Unlike some python libraries, DScribe requires that certain code extensions are compiled during the setup. This is why gcc is required.

Hope this helps!

**Comment by lauri-codes** [comment]
Closing for now.
