### ISSUE TITLE
Possible inaccuracy of SOAP descriptors for periodic systems

### ISSUE THREAD

**Issue by anjohan** [SINGROUP/dscribe#30]
Hi,

I am using your package to calculate SOAP vectors for the atoms in my system. It is working very nicely, except that I get small deviations which manifest around the boundary when I try to classify the local structure.

To reproduce this, I have created the following example:
- Create a cubic cell with atoms.
- Redefine the cubic cell as monoclinic with an angle of 45 degrees, wrap the atoms back inside the cell.
- Compute the difference in SOAP descriptors before and after. Ideally, this should be zero (or machine precision) in a periodic system. Instead, I get about 1e-7. The Ewald matrix achieves machine precision.

The error seems to depend on the radial cutoff (which shouldn't matter.) I have attached the script and its output.

Am I interpreting these results correctly?

```python
import numpy as np
from numpy.linalg import norm
from numpy.random import normal
from ase import Atoms
from ase.visualize import view
from ase.io import write
from dscribe.descriptors import SOAP, EwaldSumMatrix

ncells = 5
natoms = 2 * ncells ** 3

# Loop over different radial cutoffs
for rcut in np.linspace(5, 8, 16):

    # Create descriptor generators
    soap_generator = SOAP(
        rcut=rcut, nmax=4, lmax=4, species=["Ni", "Ti"], periodic=True
    )
    ewald_generator = EwaldSumMatrix(natoms, permutation="none", flatten=False)

    # Define unit cell
    a = 2.993
    niti = Atoms(
        "NiTi",
        positions=[[0.0, 0.0, 0.0], [a / 2, a / 2, a / 2]],
        cell=[a, a, a],
        pbc=[1, 1, 1],
    )

    # Replicate system
    niti = niti * ncells
    a *= ncells

    # Add some noise to positions
    positions = niti.get_positions()
    noise = normal(size=positions.shape)
    niti.set_positions(positions + noise)
    niti.wrap()

    # Write positions of orthogonal unit cell
    write("orthogonal.xyz", niti)

    # Evaluate descriptors for orthogonal unit cell
    orthogonal_soaps = soap_generator.create(niti)
    orthogonal_ewalds = ewald_generator.create(niti)

    # Redefine the cubic unit cell as monoclinic
    # with a 45-degree angle,
    # this should not affect the descriptors
    niti.set_cell([[a, 0, 0], [0, a, 0], [a, 0, a]])
    niti.wrap()

    write("nonorthogonal.xyz", niti)

    # Evaluate descriptors for new, monoclinic unit cell
    non_orthogonal_soaps = soap_generator.create(niti)
    non_orthogonal_ewalds = ewald_generator.create(niti)

    # Calculate error for the two descriptors
    soap_error = norm(orthogonal_soaps - non_orthogonal_soaps) / norm(orthogonal_soaps)
    ewald_error = norm(orthogonal_ewalds - non_orthogonal_ewalds) / norm(
        orthogonal_ewalds
    )
    print(
        f"rcut = {rcut:.2e}, SOAP error: {soap_error:.2e}, Ewald error: {ewald_error:.2e}"
    )

"""
Sample output:
rcut = 5.00e+00, SOAP error: 0.00e+00, Ewald error: 1.19e-15
rcut = 5.20e+00, SOAP error: 0.00e+00, Ewald error: 1.14e-15
rcut = 5.40e+00, SOAP error: 0.00e+00, Ewald error: 1.54e-15
rcut = 5.60e+00, SOAP error: 0.00e+00, Ewald error: 7.71e-16
rcut = 5.80e+00, SOAP error: 0.00e+00, Ewald error: 9.89e-16
rcut = 6.00e+00, SOAP error: 1.62e-08, Ewald error: 7.77e-16
rcut = 6.20e+00, SOAP error: 1.27e-08, Ewald error: 7.33e-16
rcut = 6.40e+00, SOAP error: 3.32e-08, Ewald error: 1.03e-15
rcut = 6.60e+00, SOAP error: 5.91e-08, Ewald error: 1.10e-15
rcut = 6.80e+00, SOAP error: 2.20e-07, Ewald error: 1.61e-15
rcut = 7.00e+00, SOAP error: 2.26e-07, Ewald error: 9.01e-16
rcut = 7.20e+00, SOAP error: 2.99e-07, Ewald error: 1.14e-15
rcut = 7.40e+00, SOAP error: 1.13e-06, Ewald error: 1.33e-15
rcut = 7.60e+00, SOAP error: 0.00e+00, Ewald error: 1.28e-15
rcut = 7.80e+00, SOAP error: 0.00e+00, Ewald error: 1.61e-15
rcut = 8.00e+00, SOAP error: 0.00e+00, Ewald error: 9.49e-16
"""
```

**Comment by lauri-codes** [comment]
Hi @anjohan!

Thanks for your message. I will look into this and let you know when I
figure out what is going on.

**Comment by lauri-codes** [comment]
Hi @anjohan!

The error seems to be isolated to the newest pip version 0.2.9. For a quick fix, use an older version, e.g. 0.2.8. I will try to make a hotfix ASAP.

**Comment by anjohan** [comment]
Thank you very much for the quick response and solution!

This does indeed remove the error for my test case. I had noticed that the periodicity code was evolving, so I tried the newest (Github) version as well, but I didn't think to try older versions.

If it helps in your debugging, I noticed that the error goes away if you don't add the noise to the coordinates, i.e. when the structure is a perfect crystal.

There is still some boundary problem for my "real" application, but that is probably on my end now that dscribe handles the periodicity correctly for the test case above.

**Comment by lauri-codes** [comment]
Brief update: It seems that after wrapping the atoms to the new monoclinic cell (`niti.wrap()`), the atomic configuration near the boundaries is not completely identical with the cubic case. This is because the wrapping may throw some atoms to the other side of the cell if they near the border (see the `eps` parameter in atoms.wrap()). The effect is pronounced in your example by the fact that the system is very big == there is a lot of boundary.

I will have to see if it makes sense to increase the default padding that we use to prevent these boundary effects. I wouldn't want to crank this padding too high, because large values incur a performance penalty when extending the system.

For most applications this error is still relatively small. I will have to think about a clever way to decide the padding for the next release.

**Comment by anjohan** [comment]
Thank you for the update and continued effort.

With the downgrade to 0.2.8 and a bugfix in my own handling of triclinic cells, the SOAP vectors now work perfectly for my application!

**Comment by lauri-codes** [comment]
The master branch is now updated with a version that uses larger padding that also scales according to the provided sigma value. This version is accompanied by a new regression test (roughly based on the code provided above) that checks the accuracy with different cutoffs, sigmas and cell sizes.

**Comment by lauri-codes** [comment]
The fix to this issue can now be found in version 0.3.0.
