### ISSUE TITLE
Only consider part of the total atom species? 

### ISSUE THREAD

**Issue by wushanyun64** [SINGROUP/dscribe#36]
Hi,

When SOAP is dealing with a dataset with a wide variety of atom species, the size of the descriptor can get very large (for my case 300K). With the size of descriptor like this, train a regression model can be very time consuming as well as not really make sense. (since the number of features is way bigger than the number of structures). So is it possible to calculate SOAP only on a **selected set** or a **sub-set** of atomic species instead of on the **whole set** of atom species?

**Comment by lauri-codes** [comment]
Hi @wushanyun64,

It depends on what you mean by calculating SOAP on a subset of elements? You can definitely just select a subset of chemical species and provide it in the `species`-argument. Then just remove all structures in the dataset that contain species outside this subset. But I guess this is not what you mean?

If you instead wish to approximate the chemical and structural diversity of the original dataset, there are different things you can try:

- Use a dimensionality reduction technique of your choice (e.g. PCA, t-SNE) before regression.
- Try disabling the crossover terms in the SOAP spectrum with `crossover=False` (currently enabled only for the gto radial basis). This will make the output scaled linearly with respect to the number of chemical species, as opposed to the quadratic scaling that is the default. However, this will make the output less detailed, as cross-over terms between atomic elements will be completely disabled. It is up to you to choose whether this is acceptable or not in your applications.
- You can group multiple chemical elements under a "pseudo-species", e.g. use one species for each column of the periodic table. There are some clever ways for doing such grouping that you can find in the literature.

Hope this helps

**Comment by wushanyun64** [comment]
Hi Lauri:

Thank you for the advice, it's really helpful. I definitely want to preserve the diversity for the structures in the dataset cause there's no dominant combination of atom species there. let me try pca first and see what happens. 

Thank again.

**Comment by wushanyun64** [comment]
> Hi @wushanyun64,
> 
> It depends on what you mean by calculating SOAP on a subset of elements? You can definitely just select a subset of chemical species and provide it in the `species`-argument. Then just remove all structures in the dataset that contain species outside this subset. But I guess this is not what you mean?
> 
> If you instead wish to approximate the chemical and structural diversity of the original dataset, there are different things you can try:
> 
> * Use a dimensionality reduction technique of your choice (e.g. PCA, t-SNE) before regression.
> * Try disabling the crossover terms in the SOAP spectrum with `crossover=False` (currently enabled only for the gto radial basis). This will make the output scaled linearly with respect to the number of chemical species, as opposed to the quadratic scaling that is the default. However, this will make the output less detailed, as cross-over terms between atomic elements will be completely disabled. It is up to you to choose whether this is acceptable or not in your applications.
> * You can group multiple chemical elements under a "pseudo-species", e.g. use one species for each column of the periodic table. There are some clever ways for doing such grouping that you can find in the literature.
> 
> Hope this helps

Hi Lauri:

Thanks again for your help. Here's a quick follow up question about the third comment from you, the 'pseudo-species' method sounds very interesting to me but it seems hard to find relevant info online. Can you elaborate a little more about that, or simply point me to a paper? Thank you!

**Comment by lauri-codes** [comment]
Here are two papers that I have come across:
- [doi.org/10.1039/c8cp05921g](https://doi.org/10.1039/c8cp05921g)
- [doi.org/10.1063/1.5108803](https://doi.org/10.1063/1.5108803)
