### ISSUE TITLE
failed to install Dsribe on win10 system

### ISSUE THREAD

**Issue by hewg2008** [SINGROUP/dscribe#37]
I was so glad to see your package of Dsribe, but I failed to install it on my windows system. I wonder whether you could help me install your package on windows system, or provide a installation guide for windows system. Thanks.

**Comment by lauri-codes** [comment]
Hi @hewg2008!

It is possible to install dscribe on a Win10 computer, but you will have to use the [Windows Subsystem for Linux (WSL)](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux). This is also mentioned in the [installation manual](https://singroup.github.io/dscribe/install.html). This in practice means that you will have to install a Linux distribution that runs inside your Windows OS, and you will use it to run install and run the dscribe code.

Unfortunately we do not supoprt a native Windows installation, but the WSL approach has seemed to work for now. Hope this helps.

**Comment by hewg2008** [comment]
Thanks, I have already installed it on Linux system.
