### ISSUE TITLE
OQMD database

### ISSUE THREAD

**Issue by lmj1029123** [SINGROUP/dscribe#39]
Hi,

I am trying to reproduce the result for the formation energy prediction on the OQMD data. Could I know the way you guys query the OQMD database to get 222215 data points? 

When I do the first filtering to get the converged samples with,

`FormE = FormationEnergy.objects.filter(calculation__converged=True)
print(FormE.count())`

I get 309107 samples instead of 239426 as indicated in the paper. Am I doing something wrong here? Thanks!

**Comment by lauri-codes** [comment]
Hi!

I would simply suggest using the accompanying data file that is mentioned in the article and found in Figshare: [https://doi.org/10.6084/m9.figshare.c.4607783](https://doi.org/10.6084/m9.figshare.c.4607783). It directly contains the used geometries, formation energies and OQMD identifiers for all the used 222215 samples from OQMD. If you want to retrieve the data from OQMD directly, make sure that you use OQMD 1.1.
