### ISSUE TITLE
pip install error on ase main (development) branch

### ISSUE THREAD

**Issue by yashasvi-ranawat** [SINGROUP/dscribe#41]
ERROR: dscribe 0.3.2 has requirement ase>=3.19.0, but you'll have ase 3.19.0b1 which is incompatible.

Is there an easy fix to that?

**Comment by lauri-codes** [comment]
What kind of error are you getting? I could check it out.

**Comment by lauri-codes** [comment]
Closing this for now as inactive, you can reopen @yashasvi-ranawat if you still need help.
