### ISSUE TITLE
extracting features using MBTR for crystals

### ISSUE THREAD

**Issue by k-kian** [SINGROUP/dscribe#47]
Dear Lauri,

I would like to use MBTR to train a dataset of crystalline systems. I have 6000 data points and my dataset consists of ~88 different elements. Using get_number_of_features()-function, I got 1 x 33695100 for the size of vectors for each periodic crystal which is extremely big and sparse. Therefore it takes forever to extract features for my dataset. Am I doing something wrong or for MBTR such big vectors are normal?

In addition, it seems that there are many parameters in MBTR that need to be tuned for k1,k2 and k3. Considering the above issue, examining all possible combinations of these parameters will become really time consuming. I am wondering if you have any suggestion to get around these issues. 

Thanks much for your time!

**Comment by lauri-codes** [comment]
Hi @k-kian,

I would suggest that you take at the [supplementary information that is associated with the dscribe article](https://ars.els-cdn.com/content/image/1-s2.0-S0010465519303042-mmc1.pdf). It contains some tips on optimizing MBTR hyperparameters, as well as some sane defaults that might be suitable for your case. In the article, we used MBTR with a dataset of > 200 K crystals with around 80-90 different elements.

In general as soon as you turn on k3, the number of features explodes. However, if you can deal with sparse matrices this should not be a problem.

Hope this helps!

**Comment by k-kian** [comment]
Hi Lauri,

Thanks much for your quick reply. It was a big help. I would like to kindly ask you: 

1- Would it be fine to only use k1 when optimizing k1 parameters (similarly using only k2 and k3 when optimizing k2 and k3 parameters, respectively)?

2- In the supplementary information that is associated with the dscribe article, I noticed that you have only optimized "sigma" and "scale" parameters for MBTR when optimizing k1,k2, and k3. I am wondering which values you used for other parameters, for example for "min ","max" and "n" parameters for the "grid" of k3.

3- I did a quick test, and it seems that regardless of turning sparse to 'True' or 'False', calculating the matrices are slow. I am wondering if turning sparse to True can help in making the features extraction faster.

Once again, I appreciate your time!

Kian

**Comment by lauri-codes** [comment]
1. This is what we did at least. I think it is perfectly fine, and the only viable option with big datasets.

2. `min` and `max you` can directly determine from your dataset, e.g. for k1 they are your min/max atomic numbers, for k2 the min/max atomic distances, for k3 the min/max angles. `n` just needs to be high enough to capture the relevant features: something between 50-200 is probably fine.

3. The `sparse` option does not affect speed much. The weighting options affect the speed the most: if `scale` is very low for k2 and k3, a large number of periodic neighbors will need to be taken into account, making the calculation slow.

**Comment by k-kian** [comment]
Thanks much Lauri! It was indeed a great help. Following your advice, I can see that the higher the "scale" in k3, the faster the calculations are. I am not sure, where one should put the cut off beyond which accounting larger number of periodic neighbours will not affect, though. My understanding is that for MBTR and ACSF, it is very difficult to narrow down the grid of parameters in advance, unless one tries them. 

In addition, if I want to train my model for two different properties (labels), lets say P1 and P2, do you think the optimized parameter for P1 can be used for P2 as well? or one needs to optimize parameters for P1 and P2 separately?

**Comment by lauri-codes** [comment]
Hi @k-kian,

Indeed it can be hard to find a good set of values. If you are working with a machine learning problem, then thorough cross-validation is the best option, but that can quickly become computationally heavy.

In general, you cannot assume that the hyperparameters are entirely transferable across different properties. But typically the hyperparameters will not change too much between different properties, so you can some kind of sense of the range they should be in.

**Comment by lauri-codes** [comment]
Closing for now.
