### ISSUE TITLE
typo in the main README

### ISSUE THREAD

**Issue by gabor1** [SINGROUP/dscribe#50]
hi !

in the main readme, you have "Smooth Overlap of Atomic Orbitals (SOAP)" . the P in SOAP stands for "Positions" not for "Orbitals". Doing orbitals (so varying the Gaussians that are placed on atoms, perhaps adding l>0 functions on each neighbour) is an interesting idea, I am not aware of anyone trying that for an environment - it is related to Stefan Goedecker's fingerprints (but after placing the orbitals, he doesn't compute the rotationally invariant overlap, he diagonalises the overlap matrix to get his fingerprints).

**Comment by lauri-codes** [comment]
Thanks for pointing this out, it is now fixed. Indeed in some cases, it might be very interesting to use actual orbitals. If orbitals are already available in the initial dataset, then doing predictions for some computationally heavy quantities might be doable through ML.
