### ISSUE TITLE
Reading in molecules

### ISSUE THREAD

**Issue by dangthatsright** [SINGROUP/dscribe#51]
Hello apologies if this has an easy solution, if so then it is very hard to find.

I would like to use library however it doesn't seem like there are any examples of reading in many molecules. I am looking to work with either sdfs or rdkit mols but it is very hard to transform them into whatever data structure you are using.

Can you please have an example of creating structures by reading in an sdf with multiple molecules or with a list of rdkit mols? I can also convert sdf to xyz but I don't know how to get xyz file with multiple molecules into multiple structures.

**Comment by lauri-codes** [comment]
Hi!

The basic tutorial should cover this to some extent. If you look at [the first step](https://singroup.github.io/dscribe/tutorials/basics.html#typical-workflow) in that tutorial, it shows you that you need to transform your structures into ASE.Atoms. In your case, you just need to call the read function from ASE on e.g. your sdf-file. If your sdf file contains multiple molecules, the `ase.io.read` function can return a list of all of them (by using the argument `index=":"`) You can find more details about the [I/O capabilities of ASE at their homepage.](https://wiki.fysik.dtu.dk/ase/ase/io/io.html) Perhaps I could add a separate tutorial for working with larger datasets.

Hope this helps!

**Comment by dangthatsright** [comment]
Hi, thank I think part of the reason was I never heard of ASE before. Passing in index=":" still gives only the first molecule. Looking at `ase.io.sdf.read_sdf` https://wiki.fysik.dtu.dk/ase/_modules/ase/io/sdf.html#read_sdf it seems like they only read the first molecule as well. I could get around this but I was wondering what do you do for larger datasets. Are you really storing hundreds of thousands of files somewhere?

**Comment by lauri-codes** [comment]
Hi,

You're right: ASE seems to actually have a very limited support for sdf files. If you want to stick to sdf files, you will have to read them with some other software and then [construct ase.Atoms from them](https://wiki.fysik.dtu.dk/ase/ase/atoms.html). This should be easy, if you have problems let me know.

As for using multiple configurations in general: It definitely makes sense to store large datasets in a single file. In the [ASE.io page](https://wiki.fysik.dtu.dk/ase/ase/io/io.html), you can see a table of the file formats that support reading and writing multiple configurations. I have typically used the extended xyz-format (.extxyz).

Just out of curiosity, what kind of data structure do you use to work with atomistic structures? Are you using some other library or something custom? So far ASE has been the easiest to work with, so we went with it. But if there are better and more widely accepted alternatives then we can reconsider.

**Comment by dangthatsright** [comment]
I primarily work with protein / ligand interactions and proteins are usually in pdb format, whereas ligands are usually sdfs. I have not seen ASE or xyz be used in many places. The main library that we use is RDKit, so a direct way to go from RDKit to ASE would be good, but RDKit to your featurizations would be best. 

Right now I am doing RDKit to sdf to ASE which doesn't seem great, but at least it works :P
