### ISSUE TITLE
Modifications for LMBTR for Element Encoding

### ISSUE THREAD

**Issue by vinsonliao** [SINGROUP/dscribe#52]
Hi there!

I was wondering if there was anyway to encode elemental identity in LMBTR. I understand that the traditional MBTR doesn't exactly work, but is there a way the user could prescribe a custom distance metric that is compatible with the system at hand?

Thanks!

**Comment by lauri-codes** [comment]
Hi!

Yes, it might be reasonable to come up with some form of a k=1 term for LMBTR as well. I guess we could just add the possibility of using a radial weighting from the local center that would be applied to the Gaussians. Is that something you would be interested in? The resulting spectrum would crudely tell which atomic species are most prominent near a point.

**Comment by vinsonliao** [comment]
Yes, that would definitely be very useful. Do you have any suggestions on how this functionality could be added on the user end?

**Comment by lauri-codes** [comment]
You mean how the end user would configure the weighting? I would  implement it like this:
```python
lmbtr = LMBTR(
    species=["H", "O"],
    k1={
        "geometry": {"function": "atomic_number"},
        "grid": {"min": 0, "max": 100, "n": 100, "sigma": 0.1},
        "weighting": {"function": "exponential", "scale": 0.5, "cutoff": 1e-3},
    }, ...
)
```

We can also quite easily add new weighting functions. Any suggestions for them are welcome.

**Comment by lauri-codes** [comment]
Closing for now, reopen again if still relevant.
