### ISSUE TITLE
formula for SOAP power spectrum in the tutorial.

### ISSUE THREAD

**Issue by negf** [SINGROUP/dscribe#54]
Hi,

In the tutorial the power spectrum as well as the expansion coefficients depend on r, however the r dependency should be integrated out. So the r dependency in p(r) and c^Z_nlm(r) should be dropped, shouldn't it?

**Comment by lauri-codes** [comment]
Hi @negf,

In this context, `r` does not refer to the integration variable. It instead refers to the position that you have chosen as a center for the SOAP spectrum. As you said, the radial variable in the integration has already been integrated out.

I can see that this is confusing. Do you think that renaming the variable to `R` and documenting the difference better would be a good idea?

**Comment by negf** [comment]
ok I see. That is indeed a bit confusing. Yes I think using R or R_i (where i is the i-th atom) would be more clear. Or as far as I understand the basis functions are always centered at the position R_i of the atom so simply i as index would suffice, because I could think of the power spectrum as a 2D matrix where the i-th row is given by the components of p(R_i), isn't this what you output anyways (in some flattened form).

**Comment by lauri-codes** [comment]
The SOAP spectrum can be calculated at any arbitrary point in space, so R does not have to correspond to an atoms position. But more generally R_i would refer to the ith position for which the spectrum was requested.

I will update the docs so that all this is clearer. Thanks again for the feedback!

**Comment by Aki78** [comment]
That is a good point. r_i gives the impression of the spectrum always being on top of the atoms though, maybe x in vector format would be clearer, since it can be anywhere in space.

**Comment by lauri-codes** [comment]
Fixed in the upcoming version 1.1.0.
