### ISSUE TITLE
installation error with pip 

### ISSUE THREAD

**Issue by beef-broccoli** [SINGROUP/dscribe#57]
Hello, 

I'm getting the following error when I tried to install dscribe (Mac OS Big Sur 11.1)

I used a clean conda environment with numpy and scipy, ran `pip install dscribe` and got this error. From my understanding, it looks like some files are missing from the source? Tried to build it from github source as suggested by the documentation, got the same errors. 

Any advice? Thanks in advance. 

Processing /Users/mac/dscribe
Requirement already satisfied: pybind11>=2.4 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (2.6.1)
Requirement already satisfied: numpy in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (1.19.2)
Requirement already satisfied: scipy in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (1.5.2)
Requirement already satisfied: ase>=3.19.0 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (3.21.0)
Requirement already satisfied: scikit-learn in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (0.24.1)
Requirement already satisfied: joblib in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from dscribe==0.4.1a0) (1.0.0)
Requirement already satisfied: matplotlib>=2.0.0 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from ase>=3.19.0->dscribe==0.4.1a0) (3.3.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (8.1.0)
Requirement already satisfied: six in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=2.0.0->ase>=3.19.0->dscribe==0.4.1a0) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/envs/dscribe/lib/python3.9/site-packages (from scikit-learn->dscribe==0.4.1a0) (2.1.0)
Building wheels for collected packages: dscribe
  Building wheel for dscribe (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/envs/dscribe/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"'; __file__='"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-wheel-6r3d7y75
       cwd: /private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.9
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe
  copying dscribe/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
  copying dscribe/kernels/localsimilaritykernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
  copying dscribe/kernels/averagekernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
  copying dscribe/kernels/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
  copying dscribe/kernels/rematchkernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe/core
  copying dscribe/core/system.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
  copying dscribe/core/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
  copying dscribe/core/lattice.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
  copying dscribe/utils/species.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
  copying dscribe/utils/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
  copying dscribe/utils/stats.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
  copying dscribe/utils/geometry.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/descriptor.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/elementaldistribution.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/matrixdescriptor.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/soap.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/coulombmatrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/acsf.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/sinematrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/lmbtr.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  copying dscribe/descriptors/mbtr.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
  running egg_info
  creating dscribe.egg-info
  writing dscribe.egg-info/PKG-INFO
  writing dependency_links to dscribe.egg-info/dependency_links.txt
  writing requirements to dscribe.egg-info/requires.txt
  writing top-level names to dscribe.egg-info/top_level.txt
  writing manifest file 'dscribe.egg-info/SOURCES.txt'
  reading manifest file 'dscribe.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h' under directory 'dscribe/libmbtr'
  warning: no files found matching '*.cpp' under directory 'dscribe/libmbtr'
  warning: no files found matching '*.h' under directory 'dscribe/libacsf'
  warning: no files found matching '*.cpp' under directory 'dscribe/libacsf'
  writing manifest file 'dscribe.egg-info/SOURCES.txt'
  creating build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/acsf.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/acsf.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/celllist.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/celllist.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/ext.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/mbtr.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/mbtr.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/soapGTO.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/soapGTO.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/soapGeneral.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  copying dscribe/ext/soapGeneral.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
  running build_ext
  building 'dscribe.ext' extension
  creating build/temp.macosx-10.9-x86_64-3.9
  creating build/temp.macosx-10.9-x86_64-3.9/dscribe
  creating build/temp.macosx-10.9-x86_64-3.9/dscribe/ext
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/anaconda3/envs/dscribe/include -arch x86_64 -fPIC -O2 -isystem /opt/anaconda3/envs/dscribe/include -arch x86_64 -Idscribe/ext -I/opt/anaconda3/envs/dscribe/lib/python3.9/site-packages/pybind11/include -I/opt/anaconda3/envs/dscribe/lib/python3.9/site-packages/pybind11/include -I/opt/anaconda3/envs/dscribe/include/python3.9 -c dscribe/ext/acsf.cpp -o build/temp.macosx-10.9-x86_64-3.9/dscribe/ext/acsf.o -std=c++11 -O3 -fvisibility=hidden
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for dscribe
  Running setup.py clean for dscribe
Failed to build dscribe
Installing collected packages: dscribe
    Running setup.py install for dscribe ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/dscribe/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"'; __file__='"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-record-z6ylr7i5/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/envs/dscribe/include/python3.9/dscribe
         cwd: /private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/
    Complete output (65 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe
    copying dscribe/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
    copying dscribe/kernels/localsimilaritykernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
    copying dscribe/kernels/averagekernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
    copying dscribe/kernels/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
    copying dscribe/kernels/rematchkernel.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/kernels
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe/core
    copying dscribe/core/system.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
    copying dscribe/core/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
    copying dscribe/core/lattice.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/core
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
    copying dscribe/utils/species.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
    copying dscribe/utils/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
    copying dscribe/utils/stats.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
    copying dscribe/utils/geometry.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/utils
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/descriptor.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/elementaldistribution.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/matrixdescriptor.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/soap.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/coulombmatrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/acsf.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/sinematrix.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/lmbtr.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    copying dscribe/descriptors/mbtr.py -> build/lib.macosx-10.9-x86_64-3.9/dscribe/descriptors
    running egg_info
    writing dscribe.egg-info/PKG-INFO
    writing dependency_links to dscribe.egg-info/dependency_links.txt
    writing requirements to dscribe.egg-info/requires.txt
    writing top-level names to dscribe.egg-info/top_level.txt
    reading manifest file 'dscribe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.h' under directory 'dscribe/libmbtr'
    warning: no files found matching '*.cpp' under directory 'dscribe/libmbtr'
    warning: no files found matching '*.h' under directory 'dscribe/libacsf'
    warning: no files found matching '*.cpp' under directory 'dscribe/libacsf'
    writing manifest file 'dscribe.egg-info/SOURCES.txt'
    creating build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/acsf.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/acsf.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/celllist.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/celllist.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/ext.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/mbtr.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/mbtr.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/soapGTO.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/soapGTO.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/soapGeneral.cpp -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    copying dscribe/ext/soapGeneral.h -> build/lib.macosx-10.9-x86_64-3.9/dscribe/ext
    running build_ext
    building 'dscribe.ext' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/dscribe
    creating build/temp.macosx-10.9-x86_64-3.9/dscribe/ext
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/anaconda3/envs/dscribe/include -arch x86_64 -fPIC -O2 -isystem /opt/anaconda3/envs/dscribe/include -arch x86_64 -Idscribe/ext -I/opt/anaconda3/envs/dscribe/lib/python3.9/site-packages/pybind11/include -I/opt/anaconda3/envs/dscribe/lib/python3.9/site-packages/pybind11/include -I/opt/anaconda3/envs/dscribe/include/python3.9 -c dscribe/ext/acsf.cpp -o build/temp.macosx-10.9-x86_64-3.9/dscribe/ext/acsf.o -std=c++11 -O3 -fvisibility=hidden
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/envs/dscribe/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"'; __file__='"'"'/private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-req-build-466mwvg6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/l9/h3jppwwn11b0c6cct25t47yh0000gn/T/pip-record-z6ylr7i5/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/envs/dscribe/include/python3.9/dscribe Check the logs for full command output.

**Comment by beef-broccoli** [comment]
Also I have no idea why some of the fonts are big. Sorry about that

**Comment by lauri-codes** [comment]
Hi! Looks like you're missing the mac command line tools. Can you try installing them first and then retry?

**Comment by beef-broccoli** [comment]
Ohh i see. It works now. Thank you very much for the help!
