### ISSUE TITLE
SOAP descriptors of different species too similar?

### ISSUE THREAD

**Issue by ryokbys** [SINGROUP/dscribe#58]
Hi,
It's a great project.
I tried to create SOAP descriptors of a crystalline system including a few chemical species. But the obtained SOAP descriptors of other species seem too close. Attached is an example of Mg2SiO4 and the plot at the end of the notebook shows very close SOAP values for Mg, Si, and O species. I am not very sure whether it is wrong, but if I make SOAP descriptors with a different program values for the species are much different. Could you tell me if something wrong with my way of creating SOAP?

Versions
- dscribe   0.4.0
- ase   3.20.1

![structure](https://user-images.githubusercontent.com/6027630/107722516-67a34100-6d22-11eb-93e4-bbb340ed00ff.png)
![スクリーンショット 2021-02-12 11 04 58](https://user-images.githubusercontent.com/6027630/107722493-5f4b0600-6d22-11eb-9168-0ba0522544bd.png)

```
$ cat POSCAR
Mg8 Si4 O16
1.0
4.802840 0.000000 0.000000
0.000000 6.047893 0.000000
0.000000 0.000000 10.323355
Mg Si O
8 4 16
direct
0.000000 0.000000 0.000000 Mg
0.500000 0.000000 0.500000 Mg
0.000000 0.500000 0.000000 Mg
0.500000 0.500000 0.500000 Mg
0.008375 0.750000 0.277264 Mg
0.508375 0.250000 0.222736 Mg
0.991625 0.250000 0.722736 Mg
0.491625 0.750000 0.777264 Mg
0.925974 0.750000 0.593638 Si
0.425974 0.250000 0.906362 Si
0.074026 0.250000 0.406362 Si
0.574026 0.750000 0.093638 Si
0.276946 0.466986 0.837165 O
0.776946 0.533014 0.662835 O
0.723054 0.966986 0.162835 O
0.223054 0.033014 0.337165 O
0.723054 0.533014 0.162835 O
0.223054 0.466986 0.337165 O
0.276946 0.033014 0.837165 O
0.776946 0.966986 0.662835 O
0.777851 0.750000 0.446782 O
0.277851 0.250000 0.053218 O
0.222149 0.250000 0.553218 O
0.722149 0.750000 0.946782 O
0.265961 0.750000 0.591677 O
0.765961 0.250000 0.908323 O
0.734039 0.250000 0.408323 O
0.234039 0.750000 0.091677 O
```

**Comment by lauri-codes** [comment]
Hi @ryokbys!

I don't see anything fundamentally wrong with your current setup. In the context of the original definition for SOAP (https://doi.org/10.1103/PhysRevB.87.184115), there are a few parameters you can tune if you are interested in tuning SOAP to be more sensitive to the sites:

- Reduce `rcut`
- Try `crossover=False`

Also, if you are using these descriptors in a machine learning environment, the learning algorithm hyperparameters should adjust quite well to detecting even smaller changes.

There are some ideas for improving the locality of SOAP that go beyond the original definition, see issue #20. Out of curiosity, what other code are you using, and which parameters are you using?

**Comment by ryokbys** [comment]
Thanks @lauri-codes for your quick response.

The reason why asked this is because I got the following PCA map of SOAP features obtained from polycrystalline 4-component system using DScribe, which was much different from I expected. I expected that points of each species make separate clusters. But this could be true...
![PCA_SOAP_poly](https://user-images.githubusercontent.com/6027630/107748620-b1108200-6d5c-11eb-9144-23a8b989769f.png)

Actually the PCA map obtained from crystalline of the same 4-component system, I got more reasonable-looking(?) one like the following.
![PCA_SOAP_crystal](https://user-images.githubusercontent.com/6027630/107749360-ca65fe00-6d5d-11eb-9ffb-d99ccee37880.png)

The one I used to compare SOAP descriptor is a fortran wrapper routine that calls GAP code in QUIP. But unfortunately it is not scalable to large system, that's why I am trying DScribe. The SOAP graph  obtained by it with almost the same configuration looks more different between species, but it could also be the magic of ordering of SOAP index or something.

Anyway, thanks for your advices.

**Comment by lauri-codes** [comment]
Hi @ryokbys!

Coming back to this issue in preparation for version 1.1.0: we will add a new weighting option for SOAP that will greatly increase the local resolution. Here is an example script of using it (the structure is here: [forsterite.zip](https://github.com/SINGROUP/dscribe/files/6510657/forsterite.zip)):


```python
import numpy as np
import matplotlib.pyplot as mpl
from ase.io import read
from dscribe.descriptors import SOAP

atoms = read("./forsterite.poscar")
atoms.wrap()

soap = SOAP(
    species=["Mg", "Si", "O"],
    periodic=True,
    weighting={"function": "poly", "r0": 6, "c": 1, "d": 1, "m": 4},
    nmax=4,
    lmax=3,
    crossover=True,
)
feat = soap.create(atoms)
fix, ax = mpl.subplots(figsize=(10, 5))
for index in [0, 8, 24]:
    i_feat = feat[index]
    x = np.arange(0, i_feat.shape[0])
    mpl.plot(x, i_feat, label=atoms.get_chemical_symbols()[index])
mpl.legend()
mpl.tight_layout()
mpl.show()
```


This produces the following plot for your structure:
![forsterite](https://user-images.githubusercontent.com/6513318/118856792-ff936680-b8df-11eb-9b3c-a2550c251149.png)

As you can see, by introducing a radial weighting that monotonuously decreases towards zero the further you go from a center (this is controlled by the new `weighting`-dictionary), you can remedy the problems discussed in issue #20. There are several parameters that you can use to tune the weighting to fit your needs. We are preparing version 1.1.0 for release, but if you want, you can already play with it by cloning branch 1.1.0 from git and installing it with

```sh
cd dscribe
pip installl .
```

**Comment by lauri-codes** [comment]
Closing this for now, please see the previous comment.

**Comment by futuring-wcy** [comment]
hi

**Comment by Guancred** [comment]
> Thanks @lauri-codes for your quick response.
> 
> The reason why asked this is because I got the following PCA map of SOAP features obtained from polycrystalline 4-component system using DScribe, which was much different from I expected. I expected that points of each species make separate clusters. But this could be true... ![PCA_SOAP_poly](https://user-images.githubusercontent.com/6027630/107748620-b1108200-6d5c-11eb-9144-23a8b989769f.png)
> 
> Actually the PCA map obtained from crystalline of the same 4-component system, I got more reasonable-looking(?) one like the following. ![PCA_SOAP_crystal](https://user-images.githubusercontent.com/6027630/107749360-ca65fe00-6d5d-11eb-9ffb-d99ccee37880.png)
> 
> The one I used to compare SOAP descriptor is a fortran wrapper routine that calls GAP code in QUIP. But unfortunately it is not scalable to large system, that's why I am trying DScribe. The SOAP graph obtained by it with almost the same configuration looks more different between species, but it could also be the magic of ordering of SOAP index or something.
> 
> Anyway, thanks for your advices.

Hello,
Could you tell me what's mean of the x, y axis and colorbar in the map?
![image](https://github.com/SINGROUP/dscribe/assets/91767936/381d63da-2dab-4756-a057-50d854f876fa)

**Comment by ryokbys** [comment]
As I remember correctly, x and y are PCA1 and PCA2 values, respectively. And the colorbar value is species ID of the 4-component system, e.g., 1: Li, 2: La, 3: Zr, 4:O.
