### ISSUE TITLE
Unable to set n_jobs to -1

### ISSUE THREAD

**Issue by rajathsalegame** [SINGROUP/dscribe#59]
Hi, I'm trying to parallelize calculation of SOAP descriptors and would like to use the maximum number of CPUs available on my system. When trying to set `n_jobs=-1` in `soap_generator.create()`, I get the error below:

`  File "/home/rajathsalegame/miniconda3/envs/chem/lib/python3.8/site-packages/dscribe/descriptors/soap.py", line 238, in create
    output = self.create_parallel(inp, self.create_single, n_jobs, output_sizes, verbose=verbose)
File "/home/rajathsalegame/miniconda3/envs/chem/lib/python3.8/site-packages/dscribe/descriptors/descriptor.py", line 307, in create_parallel
    results = np.concatenate(vec_lists, axis=0)
File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate`

Of course, it's not a huge issue as I can simply set `n_jobs = os.cpu_count()` but since you are using `joblib.Parallel` to facilitate parallelization, it would be syntactically nice if setting `n_jobs=-1` corresponded to using the maximum number of processors as is the case in `joblib`.

**Comment by lauri-codes** [comment]
Hi @rajathsalegame!

You're absolutely right. I will add support for this in the upcoming 0.5.0 version.

**Comment by lauri-codes** [comment]
Now fixed in 1.0.0.
