### ISSUE TITLE
Dimensions of SOAP

### ISSUE THREAD

**Issue by shinkiyohara** [SINGROUP/dscribe#65]
Dear all,

Hi, I am using SOAP class to calculate power spectra.
I am trying to calculate  power spectra of  crystal Cs2O including 8 Cs and 4 O atoms.
My script described below output (12, 330)-shaped numpy array.

>> soap=SOAP(rcut=6, nmax=5, lmax=5, rbf='gto', species=['Cs','O'], periodic=True, sparse=False)

When I checked the output indices correspond to a particular species combination by get_localtion function, I got below.
>> soap.get_location(('O','O')) # output slice(0, 90, None)
>> soap.get_location(('Cs','O')) # output slice(90, 240, None)
>> soap.get_location(('Cs','Cs')) #output slice(240, 330, None)

According to the pseudo-code of soap, my script should output the same dimensions power spectra regarding each species combinations, but I got different dimensional power spectra.
"pseudo-code of soap,"
for Z in atomic numbers in increasing order:
   for Z' in atomic numbers in increasing order:
      for l in range(l_max+1):
         for n in range(n_max):
            for n' in range(n_max):
               if (n', Z') >= (n, Z):
                  append p(\chi)^{Z Z'}_{n n' l}` to output

Why were their dimensions different?

Any help would be appreciated.

Thanks in advance.

Shin

------------------
Additionally writing, this problem seems to be same as  issue #48. This bag was fixed in Dscribe since version 0.4.0, but
I still got the bag in version 1.0.0.

**Comment by lauri-codes** [comment]
Hi @shinkiyohara!

Sorry for the late reply. What you are seeing is the correct behaviour, which was introduced by fixing #48 in 0.4.0. The cross-species terms with non-identical species (in your case O-Cs) have slightly more elements in them, because they do not have the same symmetry as cross-species terms with identical species (O-O, Cs-Cs).

The pseudo-code is a bit simplified but is demonstrating the correct behaviour. Here is a slightly more explicit python version that shows the output construction:

```python
from collections import defaultdict

# Atomic numbers for oxygen and cesium, sorted
atomic_numbers_sorted = sorted([8, 55])
nmax = 5
lmax = 5

# Stores the number of features for each pair of elements
soap_map = defaultdict(int)

# Fill the soap mapping accoding to the pseudocode logic
for Z1 in atomic_numbers_sorted:
   for Z2 in atomic_numbers_sorted:
      for l in range(lmax+1):
         for n1 in range(nmax):
            for n2 in range(nmax):
               if (n2, Z2) >= (n1, Z1):
                   soap_map[f"{min(Z1, Z2)}-{max(Z1, Z2)}"] += 1

# Print out the mapping
for k, v in soap_map.items():
    print(f"Number of elements for pair ({k}): {v}")
```
The output will be:
```
Number of elements for pair (8-8): 90
Number of elements for pair (8-55): 150
Number of elements for pair (55-55): 90
```

Hope this helps!

**Comment by shinkiyohara** [comment]
Thank you for your reply, Lauri!

I misunderstood that the final condition meant (n2 >= n1 ) and (Z2 >= Z1).
Now, I fully understood.

Thanks again!

Shin

**Comment by lauri-codes** [comment]
Great!
