### ISSUE TITLE
change default SOAP datatype to float64

### ISSUE THREAD

**Issue by sandipde** [SINGROUP/dscribe#66]
Hello,
      I started working with the refactored new versions 1.0.x  this week and found my perfect ML examples with SOAP descripters broke. lapack solver from sklearn complained and crashed for the optimal paramaters I had before. After spending quite some time investigating the issues I found the issue is casued by the change in default datatype in your soap routine  to "float32" conclusively.  Changing it to float64 again made the problem gone. I think I was lucky to have a problem in the right time to discover this crucial borderline issue which otherwise would have been hard to detect and diaganose.  I would strongly recommend to make the default datatype back to float64 and let the user decide if they want to change it to float32 to save memory.   As this choice potentiallly makes or brakes  your application.
Thanks. 
Best Regards
Sandip

**Comment by lauri-codes** [comment]
Hi @sandipde!

Thank you very much for bringing this up. You are right in that we should set `float64` as the default for all descriptor values, since it is the safer option. I can do this as I add the `dtype`-parameter to other descriptors as well.

**Comment by lauri-codes** [comment]
Now changed in 1.1.0.
