### ISSUE TITLE
Global similarity

### ISSUE THREAD

**Issue by zdcao121** [SINGROUP/dscribe#67]
Hi,
It's a great project.
I try to calculate the global similarity between different molecule and crystal structures. But I don't know whether the workflow of calculation is right. Attached is an example of calculating the global similarity between H2O and H2O2 molecule (using the example in the DScribe Tutorials). Could you tell me if something wrong with my way of calculating global similarity?
![example](https://user-images.githubusercontent.com/49519744/122665179-58ecff00-d1d8-11eb-98f0-f480a1270d11.png)

**Comment by lauri-codes** [comment]
Hi @zdcao121!

Sorry that answering took so long, purely my mistake for forgetting to answer.

I don't see any fundamental issues with your code. The best parameters (rcut, nmax, lmax, sigma, etc.) heavily depend on the application, so I would strongly advise you to somehow optimize them for your data.

The only small issue I can see is that you are including too many species in your example (species 6, 7 are unnecessary for this "dataset", this mistake was also in our examples). I don't think it affects the output at all, but in general keeping the number of species small is beneficial.

**Comment by zdcao121** [comment]
Thanks @lauri-codes for your response.
I watched the codes of AverageKernel  and found that the global similarity calculated in the kernel was also derived from the pair-wise matrix. The difference between the kernel and my codes is that the normalization is not applied in my codes. After applying it, they get the same results.

**Comment by lauri-codes** [comment]
Ok, great. Closing.
