### ISSUE TITLE
MBTR about mbtr.create()  ---displays only features 

### ISSUE THREAD

**Issue by muu4649** [SINGROUP/dscribe#7]
HI! I have a question. When I use mbtr.create() , it returns array with shape[positon, features] such as below.

  (0, 0)	0.00844207
  (0, 1)	0.012111196
  (0, 2)	0.01720821
  (0, 3)	0.024216358
  (0, 4)	0.033753663
  (0, 5)	0.046600137
......

I want to display only features such as below .

0.00844207
0.012111196
0.01720821
0.024216358
0.033753663
0.046600137

How should I do?

Thanks!

**Comment by muu4649** [comment]
Thank you so much!!  And Sorry I overlooked that.

I came up to one question after this . (I shouldn't write it in this issue)
 Original paper expressed that canonical choices of gk for 'k' =1,2,3,4....
But , dscribe module's 'k' is from 1 to 3.
In dscribe perhaps k=1 : atom counts, k=2 : (inverse) distances, k=3 : angles, I think.
Is  dihedral angles(k=4) not included in dscribe?
Best regards

**Comment by marchunter** [comment]
You are right, dihedral would be the logical continuation. So far, k = 4 is not implemented since for machine learning it generally does not improve the overall accuracy. Unless there is a clear need from the users' side, we leave it at k = 3.

**Comment by muu4649** [comment]
OK.Thanks!
