### ISSUE TITLE
'nan' value occur in acsf descriptors

### ISSUE THREAD

**Issue by zjujdj** [SINGROUP/dscribe#70]
hello,
i calculated the acsf descriptors for the atoms in a protein using following codes(dscribe==1.1.0), and i was confused by 'nan' value could occur for some atoms, does anyone know why? thanks.

**# codes**
```python
import torch
from rdkit import Chem
import numpy as np
import pickle
from ase import Atoms
with open(r'C:\Users\15766\Desktop\1A2K_complex.3450_19.71_0', 'rb') as f:
    ligand, pocket = pickle.load(f)
atom_ls = []
atom_ls.extend([atom.GetSymbol() for atom in ligand.GetAtoms()])
atom_ls.extend([atom.GetSymbol() for atom in pocket.GetAtoms()])
atom_positions = np.concatenate([ligand.GetConformer().GetPositions(), pocket.GetConformer().GetPositions()], axis=0)
mol = Atoms(symbols=atom_ls, positions=atom_positions)
from dscribe.descriptors import ACSF
acsf = ACSF(
    species=['C', 'O', 'N', 'S', 'P', 'F', 'Cl', 'Br', 'I'],
    rcut=12.0,
    g2_params=[[4.0, 3.17]],
    g4_params=[[0.1, 3.14, 1]],
)
res = acsf.create(mol)
res_th = torch.tensor(res, dtype=torch.float)
print(torch.any(torch.isnan(res_th)))
print(np.where(torch.isnan(res_th)))
res_th[1690]
```

**# outputs**
```python
tensor(True)
(array([1690], dtype=int64), array([19], dtype=int64))
Out[92]: 
tensor([2.7536e+01, 1.7760e+00, 5.9737e+00, 7.7800e-01, 4.8037e+00, 4.7535e-07,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        3.9842e+00,        nan, 1.3123e-02, 8.6276e-02, 2.6853e-02, 8.8496e-04,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00])
```

**# original file**
[1A2K_complex.3450_19.71_0](https://drive.google.com/file/d/10xV5EdDLngVW3jokew7h1Nd-sOo9kQic/view?usp=sharing)

**Comment by lauri-codes** [comment]
Hi @zjujdj!

I think this is a case of some kind of a floating point overflow. Maybe at some point your G4 terms get a really large value for an exponent (since you have a very large system and large cutoff), which causes numerical problems. On my machine simply slightly decreasing rcut got rid of the problem. I can try and see if this particular case is fixable by increasing the precision on some of our internal variables.

**Comment by zjujdj** [comment]
Hi @lauri-codes :
many thanks for your timely reply, i tried a smller rcut value of 8A, it did slove many problematic cases, but not all. my system are some big ppi complexes, and i guess 8A is a reasonable cutoff to determine atom-atom interaction. Anyway, thanks for your suggestions.

**Comment by lauri-codes** [comment]
Hi @aneepi, @zjujdj,

Please try out the new version v1.2.0: it uses larger precision for ACSF internally and should get rid of the nan values in most cases.

**Comment by zjujdj** [comment]
@lauri-codes ,
Hi, thanks very much! i'll try the new version later!

**Comment by lauri-codes** [comment]
Ok, great! Just re-open this issue if you still experience any problems.
