### ISSUE TITLE
Please make dscribe available at conda-forge/osx-arm64 channel

### ISSUE THREAD

**Issue by kaipuolamaki** [SINGROUP/dscribe#80]
dscribe can be installed through conda-forge. dscripe is not however available for the conda-forge/osx-arm64 channel, which is native for the new Macs with M1 processors. As a work-around it is possible to install the osx-64 version, but this causes conflicts with some other numeric software releases.

**Comment by lauri-codes** [comment]
Hi @kaipuolamaki!

I can take a look at this.

**Comment by lauri-codes** [comment]
Hi @kaipuolamaki,

Can you try if you can now find and successfully install DScribe for the osx-arm64-platform? It is now added into our conda-forge setup, but I can't test it myself.

**Comment by kaipuolamaki** [comment]
Works, thanks.

```
% pwd
/Users/kaip/iCloud/Documents/dscribe/regtests
% python -t testrunner.py
Tests that an ASE Atoms is succesfully converted to a System object. ... ok
test_verbose_create (generaltests.DescriptorTests)
Tests the verbose flag in create. ... Process 0: 50.0 %
Process 0: 100.0 %
ok
[clip]
----------------------------------------------------------------------
Ran 116 tests in 45.402s

OK
```
