### ISSUE TITLE
Descsize of ASCF

### ISSUE THREAD

**Issue by zhuangyuan97** [SINGROUP/dscribe#85]
Hello，
        I have a question about descsize. In ASCF, for example, the descsize of `H2O(g2_params=[[1, 1], [1, 2], [1, 3]],
    g4_params=[[1, 1, 1], [1, 2, 1], [1, 1, -1], [1, 2, -1]],` ) in get_number_of_features is (3+1)*2+ 4*3 = 12，I thought it shuold be 3 + 4 =7，I don`t understand the n_type_pairs and n_t_types.  Forgive my poor English.

Many thanks for your contribution.

Zhuang Yuan

**Comment by lauri-codes** [comment]
Hi @zhuangyuan97,

`n_types` means the number of different atomic species (in H20 that is 2: Oxygen and Hydrogen)
`n_type_pairs` means the number of different combinations of pairs of atomic species (in H2O that is 3: O-O, H-H, O-H)

So each atomic species gets each of the G2 terms and one G1 term + each atomic species pair gets each of the G4 terms.

Hope this helps, more in-depth explanation in our [article](https://www.sciencedirect.com/science/article/pii/S0010465519303042?via%3Dihub).
