### ISSUE TITLE
Naming incosistency of rcut in SOAP and MBTR

### ISSUE THREAD

**Issue by Petkomat** [SINGROUP/dscribe#90]
Both SOAP and MBTR descriptors take cutoff radius as one of the parameters, i.e.,

- `soap = SOAP(rcut=<value>, ...)`
- `mbtr = MBTR(k2={"weighting": {"r_cut": <value>, ...}, ...)`

Probably, the naming inconsistency (`rcut` and `r_cut`) should be removed.

**Comment by lauri-codes** [comment]
Good point. Will be fixed in 1.2.2 where the docs and examples prefer the `r_cut` form, but the old names still work for backwards compatibility.

**Comment by lauri-codes** [comment]
Now fixed in v1.2.2
