### ISSUE TITLE
Numerical SOAP derivatives for periodic systems

### ISSUE THREAD

**Issue by Nilsgoe** [SINGROUP/dscribe#97]
Hi,
as mentioned in issuer #95, for  ` deriv , desc = soap.derivatives(mol, ... )` the option of calculating SOAP derivatives for periodic systems `periodic = True`  is currently not available. I would be interested in this option and hoped  it could  be added in the future.

**Comment by Aki78** [comment]
Hi,
Thank you for the suggestion. We will see what we can do, and try to get back to you in a few weeks.

**Comment by Aki78** [comment]
We have made a plan to implement soap derivatives, both numerical and analytical, on periodic systems  (with some constraints). We will make an effort to finish it by the end of this year.

**Comment by chen-jialan** [comment]
Hi, 
I want to train the nn potential to predict energy and force for materials. However, when periodic = True, and the  derivatives are not realized. So, I hope the derivatives can be applied for materials in the future

**Comment by VondrakMar** [comment]
Hey, would it be possible to use numerical derivatives for periodic systems if the lines 706 - 709 are deleted? I had tried it, and it worked, but I am not sure if I am not missing something

**Comment by lauri-codes** [comment]
Could you try installing directly from branch v2.0.0? The numerical derivatives for periodic systems are implemented there, and will be made into a new release soon.

**Comment by lauri-codes** [comment]
Now available in v2.0.0
